log:
  env: "local"
server:
  address: "192.168.1.1:8083"
  security: "tls12"
  cert: "/home/darkprof/.config/webdavd/webdav.rsa.crt"
  key: "/home/darkprof/.config/webdavd/webdav.rsa.key"
  timeout: 15s
  idle_timeout: 30s
  halt_timeout: 10s
  prefix: "/GTD"
  username: "darkprof"
  salt: "210f19e2-5b18-497a-a008-de2d6609703d"
  passhash: "48fc68263ad804944cf2cabe1dfad65c6a80e1226a977ad8aefeb90111ec4011"
  dir: "/home/darkprof/gocryptfs/GTD"
